version: "3.9"

services:
  api:
    build: .
    volumes:
      - .:/app
    command: >
      uvicorn backend.main:app
      --reload --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"

  test:
    build: .
    command: poetry run pytest -q
    profiles:
      - test 